### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BDonnot** [marota/Topology_Superposition_Theorem#2]
- [ ] remove the "target_obs" pretty much in every code in compute_power_flow (because it's always suspicious to provide the answer to the code that computes said answer, it's better to have one code to compute the answer, and then something to check if said answer is correct)
- [ ] rename pretty much all functions (names are too long, most of description is missing)
- [ ] find a representation of a grid for such code, do not make it adherent to grid2op when it does not need to
- [ ] try to code a backend from it (easiest way to run some performance checks !)
- [ ] structure better the code
